apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: openfaas-fn
spec:
  selector:
    matchLabels:
      app: todo
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: phpmeetup/frontend:1.0.23
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80