FROM node:10 as build
ADD package.json /usr/build/
WORKDIR /usr/build/
RUN npm install


FROM nginx:alpine
ADD default.conf /etc/nginx/conf.d/default.conf
ADD . /usr/share/nginx/html/
COPY --from=build /usr/build /usr/share/nginx/html
EXPOSE 80